import { IMenuOutput } from "../domain/menu-domain/entity/IMenu";
export const menuList: IMenuOutput[] = [
  {
    id: "13245",
    name: "主页",
    path: "/home",
    component: "pages/home/home",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "",
    parentNumber: "",
    microName: "",
    componentName: "home",
    sort: 0,
    isShow: true,
    type: 0,
    children: [],
  },
  {
    id: "132445765",
    name: "測試",
    path: "/test-page",
    component: "pages/test-page/test-page",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "",
    parentNumber: "",
    microName: "",
    componentName: "test-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [],
  }
]