import { IMenuOutput } from "@/shared/menu/IMenu";

export const menuList: IMenuOutput[] = [
  {
    id: "13245",
    name: "主页",
    path: "/home",
    component: "pages/home/home",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "",
    parentNumber: "",
    microName: "",
    componentName: "home",
    sort: 0,
    isShow: true,
    type: 0,
    children: [],
  },
  {
    id: "132445765",
    name: "系统管理",
    path: "/systemsetting",
    component: "pages/test-page/test-page",
    tabs: [],
    buttonClick: "",
    buttons: [],
    parentId: "000",
    icon: "",
    parentNumber: "",
    microName: "",
    componentName: "test-page",
    sort: 0,
    isShow: true,
    type: 0,
    children: [{
      id: "121212",
      name: "菜单管理",
      path: "/menu",
      component: "pages/test-page/test-page",
      tabs: [],
      buttonClick: "",
      buttons: [],
      parentId: "000",
      icon: "",
      parentNumber: "",
      microName: "",
      componentName: "test-page",
      sort: 0,
      isShow: true,
      type: 0,
      children: [],
    }],
  }
]